- type: gameMapPool
  id: DefaultMapPool
  maps:
  - Biodome
  # - Aspid
  # - Bagel
  # - Barratry
  # - Box
  # - Cluster
  # - Fland
  # - Kettle
  # - Marathon
  # - Meta
  # ##- Moose
  # - Omega
  # - Origin
  # - Saltern
